In [3]:
import numpy as np

In [4]:
# ---- THE DATA ----

student_names = np.array(["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah"])   # six students
subject_names = np.array(["Maths", "Physics", "English"])                    # three subjects

scores = np.array([[78, 65, 82],    # Aisha's three marks - one per subject, in the order above
                   [55, 71, 60],    # Ben's
                   [91, 88, 79],    # Carla's
                   [42, 38, 55],    # Dev's
                   [67, 74, 71],    # Eli's
                   [83, 97, 68]])   # Farah's

print(scores)                       # the whole table
print("shape:", scores.shape)

[[78 65 82]
 [55 71 60]
 [91 88 79]
 [42 38 55]
 [67 74 71]
 [83 97 68]]
shape: (6, 3)


In [6]:
total_marks=np.sum(scores,axis=1)
for name , total_marks in zip(student_names, total_marks):
    print(name, ":", total_marks)

Aisha : 225
Ben : 186
Carla : 258
Dev : 135
Eli : 212
Farah : 248


In [7]:
avg=np.mean(scores,axis=1)
for name , avg in zip(student_names, avg):
    print(name, ":", avg)

Aisha : 75.0
Ben : 62.0
Carla : 86.0
Dev : 45.0
Eli : 70.66666666666667
Farah : 82.66666666666667


In [9]:
average_marks = np.mean(scores,axis=0)
print(average_marks)

[69.33333333 72.16666667 69.16666667]


In [12]:
print("Hard subject is",subject_names[subject_names.argmin()])
print("Easy subject is",subject_names[subject_names.argmax()])

Hard subject is English
Easy subject is Physics
