In [1]:
import numpy as np

In [2]:
Marks = np.array([12,54,78,32,95,42])

In [3]:
# 2,3
# transpose
# mean

In [4]:
Marks = Marks.reshape(2,3)
print(Marks)

[[12 54 78]
 [32 95 42]]


In [5]:
print(Marks.mean())
print(Marks)

52.166666666666664
[[12 54 78]
 [32 95 42]]


In [6]:
Marks = Marks.T
print(Marks)

[[12 32]
 [54 95]
 [78 42]]


In [7]:
# condition score less than 40 and 80 greater

In [8]:
print(Marks[(Marks>40)&(Marks<80)])

[54 78 42]


In [9]:
Marks.size
Marks.dtype
Marks.shape

(3, 2)

In [10]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
grid = np.array([55,72,88,41,95,63,77,58,90])
grid = grid.reshape(3,3)

In [12]:
print(grid)

[[55 72 88]
 [41 95 63]
 [77 58 90]]


In [13]:
print(grid[1,2])

63


In [14]:
print(grid[1,:])

[41 95 63]


In [15]:
print(grid[:,1])

[72 95 58]


In [16]:
print(grid.sum(axis=1))

[215 199 225]


In [17]:
print(np.round(grid.mean(axis=0),1))

[57.7 75.  80.3]


In [18]:
print(grid.max())

95


In [20]:
marks = np.array([55,72,88,41,95,63])
names = np.array(["Aisha","Ben" ,"Carla" ,"Dev" ,"Eli" ,"Farah"])

In [24]:
print(names[marks>70])

['Ben' 'Carla' 'Eli']


In [31]:
print(np.sum([(marks>40) & (marks<80)]))

4


In [32]:
print(np.where(marks>80,"A","B"))

['B' 'B' 'A' 'B' 'A' 'B']
